# Generated by Django 5.0 on 2023-12-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=30)),
                ('carPrice', models.IntegerField()),
                ('carQuantity', models.IntegerField()),
                ('carImg', models.ImageField(upload_to='')),
                ('carBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.carbrand')),
            ],
        ),
    ]
