# Generated by Django 5.0 on 2023-12-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='carDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
