# Generated by Django 5.0 on 2023-12-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_cardetails_cardescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='carImg',
            field=models.ImageField(blank=True, null=True, upload_to='car/media/upload'),
        ),
    ]
