# Generated by Django 5.0 on 2023-12-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='car.cardetails'),
        ),
    ]
